### ISSUE TITLE
Can't access to PSN with FinalHE v1.8(memecore)

### ISSUE THREAD

**Issue by 1jtp8sobiu** [soarqin/finalhe#48]
> v1.8
> Support for memecore(h-encore 2.0 for VITA 3.60 support with PSN access)

In my case, I still can not access PSN on Vita1000(3.60)/PSTV(3.60).
The spoof version is set to FW 3.70. Can you confirm this?

**Comment by soarqin** [comment]
tested and confirm that it can access PSN if your account is logged in, but cannot pass fw vercheck on account login.
Since my vita was downgraded from 3.68, the account was already logged in, I didn't notice this, thank you for pointing out the problem, I will remove the instruction from README along with 1.81 release
